query ListLast10SingleSaleOffers {
    transferMarket {
      singleSaleOffers(last: 10) {
        nodes {
          
          card {
            slug
          }
          priceInFiat{eur}
        }
      }
    }
  }