query TranferMarket {
  player(slug: "josep-martinez-riera") {
    cards {
      edges {
        node {
          userOwnersWithRate {
            priceInFiat {
              eur
            }
          }
        }
      }
    }
  }
}